#!/usr/bin/env python3
"""Publish a meeting to the static site.

Inputs:
- meetings/<meeting_id>.json (metadata)
- A Whisper verbose_json transcript file with `segments[]` (e.g. transcripts/*_complete.json)

Outputs:
- docs/transcripts/<meeting_id>-data.js (TRANSCRIPT_TURNS)
- docs/transcripts/<meeting_id>.html (page that renders with docs/js/transcript-page.js)
- docs/js/search-index.js (rebuilt)

This keeps the public site static and reproducible.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]

# Allow `import scripts.transcribe` when running as a script.
sys.path.insert(0, str(REPO_ROOT))


def load_meeting(meeting_id: str) -> dict[str, Any]:
    p = REPO_ROOT / "meetings" / f"{meeting_id}.json"
    if not p.exists():
        raise SystemExit(f"Missing meeting metadata: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def normalize_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s or "").strip()


def chunk_segments(segments: list[dict[str, Any]], target_seconds: int = 30, max_chars: int = 650) -> list[dict[str, Any]]:
    """Combine small Whisper segments into larger turns for readability/search."""
    turns: list[dict[str, Any]] = []
    buf: list[str] = []
    start = None
    end = None

    def flush():
        nonlocal buf, start, end
        if start is None or end is None:
            return
        text = normalize_ws(" ".join(buf))
        if text:
            turns.append({"start": float(start), "end": float(end), "text": text})
        buf = []
        start = None
        end = None

    for seg in segments:
        s = float(seg.get("start", 0) or 0)
        e = float(seg.get("end", s) or s)
        t = str(seg.get("text", "") or "")
        t = normalize_ws(t)
        if not t:
            continue

        if start is None:
            start = s
            end = e
            buf = [t]
        else:
            end = e
            buf.append(t)

        dur = (end - start) if (start is not None and end is not None) else 0
        joined = " ".join(buf)
        # Heuristic boundaries
        if dur >= target_seconds:
            flush()
        elif len(joined) >= max_chars and re.search(r"[.!?]\s*$", joined):
            flush()

    flush()
    return turns


def label_speakers(turns: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Best-effort speaker labeling using heuristics from scripts/transcribe.py."""
    # Import without triggering yt-dlp requirements
    from scripts.transcribe import COUNCIL_MEMBERS, identify_speaker  # type: ignore

    prev = None
    out: list[dict[str, Any]] = []
    for t in turns:
        text = str(t.get("text", "") or "")
        name = identify_speaker(text, prev)
        prev = name

        speaker = "Unknown Speaker"
        if name and name != "Unknown":
            if name in COUNCIL_MEMBERS:
                title = COUNCIL_MEMBERS[name].get("title")
                if title and not str(name).lower().startswith(str(title).lower()):
                    speaker = f"{title} {name}"
                else:
                    speaker = name
            else:
                speaker = name

        out.append({
            "speaker": speaker,
            "start": float(t["start"]),
            "end": float(t["end"]),
            "text": text,
        })
    return out


def write_turns_js(meeting_id: str, turns: list[dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    js = (
        f"// Transcript turns for {meeting_id}\n"
        "// AUTO-GENERATED by scripts/publish_meeting.py (do not hand-edit)\n"
        "const TRANSCRIPT_TURNS = "
        + json.dumps(turns, indent=2, ensure_ascii=False)
        + ";\n\n"
        + "if (typeof module !== 'undefined' && module.exports) {\n"
        + "  module.exports = TRANSCRIPT_TURNS;\n"
        + "}\n"
    )
    out_path.write_text(js, encoding="utf-8")


def write_transcript_html(meeting: dict[str, Any], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    meeting_id = meeting["meeting_id"]
    display_date = meeting.get("display_date") or meeting.get("meeting_date") or ""
    title = meeting.get("title") or "Meeting"
    source_url = meeting.get("source_video_url") or ""
    portal_url = meeting.get("official_meetings_portal_url") or ""
    agenda_url = meeting.get("official_agenda_url") or ""
    minutes_url = meeting.get("official_minutes_url") or ""

    # Minimal page shell. Transcript body is rendered by docs/js/transcript-page.js
    html = f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <title>{title} - {display_date}</title>
  <link rel=\"stylesheet\" href=\"../css/style.css\">
  <link rel=\"stylesheet\" href=\"../css/transcript-page.css\">
  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">
</head>
<body>
  <div class=\"container\">
    <header class=\"meeting-header\">
      <h1><i class=\"fas fa-landmark\"></i> Fairfax City Council Meeting</h1>
      <div class=\"meta\">
        <span><i class=\"fas fa-calendar\"></i> {display_date}</span> &bull;
        <span><i class=\"fas fa-file-alt\"></i> Full Transcript</span>
      </div>
    </header>

    <div class=\"ai-notice\">
      <h4><i class=\"fas fa-robot\"></i> AI-Generated Transcript</h4>
      <p>
        This transcript was generated using AI speech recognition and best-effort speaker labeling.
        It may contain errors.
        For the official record, refer to the
        <a href=\"{source_url}\" target=\"_blank\" rel=\"noopener\">city's video archive</a>.
      </p>
    </div>

    <div class=\"official-links\">
      <h3><i class=\"fas fa-external-link-alt\"></i> Official Resources</h3>
      <p>
        <a href=\"{source_url}\" target=\"_blank\" rel=\"noopener\"><i class=\"fas fa-video\"></i> Watch Video (Granicus)</a>
        {'&bull; <a href="' + agenda_url + '" target="_blank" rel="noopener"><i class="fas fa-file-alt"></i> Agenda</a>' if agenda_url else ''}
        {'&bull; <a href="' + minutes_url + '" target="_blank" rel="noopener"><i class="fas fa-file-signature"></i> Minutes</a>' if minutes_url else ''}
        {'&bull; <a href="' + portal_url + '" target="_blank" rel="noopener"><i class="fas fa-file"></i> Meeting Portal</a>' if portal_url else ''}
      </p>
    </div>

    <div class=\"official-links\">
      <h3><i class=\"fas fa-list\"></i> Jump to section</h3>
      <div id=\"section-links\" style=\"display:flex; gap:12px; flex-wrap:wrap;\"></div>
    </div>

    <div class=\"search-container\">
      <input type=\"text\" id=\"search-input\" placeholder=\"Search within this meeting... (type to filter)\">
      <div id=\"search-count\"></div>
    </div>

    <div id=\"transcript\">
      <p style=\"color: #718096; text-align: center;\">Loading transcript…</p>
    </div>

    <button id=\"back-to-top\"><i class=\"fas fa-arrow-up\"></i> Top</button>
  </div>

  <script>
    const MEETING = {json.dumps({
        'meeting_id': meeting_id,
        'meeting_date': meeting.get('meeting_date'),
        'display_date': display_date,
        'title': title,
        'source_url': source_url,
        'official_meetings_portal_url': portal_url,
        'official_agenda_url': meeting.get('official_agenda_url'),
        'official_minutes_url': meeting.get('official_minutes_url'),
        'official_packet_url': meeting.get('official_packet_url'),
        'sections': meeting.get('sections') or [],
    }, ensure_ascii=False)};
  </script>
  <script src=\"./{meeting_id}-data.js\"></script>
  <script src=\"../js/transcript-page.js\"></script>
</body>
</html>
"""

    out_path.write_text(html, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Publish a meeting to docs/")
    ap.add_argument("meeting_id", help="Meeting id (must match meetings/<meeting_id>.json)")
    ap.add_argument("--input", "-i", required=True, help="Whisper verbose_json transcript (with segments[])")
    ap.add_argument("--chunk-seconds", type=int, default=30, help="Target chunk size in seconds")
    ap.add_argument("--max-chars", type=int, default=650, help="Max chars per chunk before forcing a boundary")
    args = ap.parse_args()

    meeting = load_meeting(args.meeting_id)
    input_path = (REPO_ROOT / args.input).resolve() if not Path(args.input).is_absolute() else Path(args.input)
    data = json.loads(input_path.read_text(encoding="utf-8"))
    segments = data.get("segments")
    if not isinstance(segments, list) or not segments:
        raise SystemExit("Input JSON missing segments[]")

    raw_turns = chunk_segments(segments, target_seconds=args.chunk_seconds, max_chars=args.max_chars)
    labeled_turns = label_speakers(raw_turns)

    turns_out = REPO_ROOT / "docs" / "transcripts" / f"{args.meeting_id}-data.js"
    html_out = REPO_ROOT / "docs" / "transcripts" / f"{args.meeting_id}.html"

    write_turns_js(args.meeting_id, labeled_turns, turns_out)
    write_transcript_html(meeting, html_out)

    # Rebuild global index
    from scripts.build_search_index import build  # type: ignore

    build()

    print(f"Published {args.meeting_id} -> {html_out} + {turns_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
